export const ROUTES = {
  DASHBOARD: "/",
  ADD_SENIOR: "/add-senior",
  VIEW_SENIORS: "/view-seniors",
  PENDING_PROFILES: "/pending-profiles",
  DECEASED_SENIORS: "/deceased-seniors",
  HELPDESK: "/helpdesk",
  OPTIONS: "/options",
  USERS: "/users",
  SENIOR_VACCINES: "/senior-vaccines",
  SENIOR_ASSISTANCES: "/senior-assistances",
  GENERATE_BACKUP: "/generate-backup",
  RESET_CODES: "/reset-codes",
  AUDIT_LOGS: "/audit-logs",

  MY_ACCOUNT: "/my-account",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
};
